### ISSUE TITLE
PEP 3107?

### ISSUE THREAD

**Issue by andiogenes** [dbakunevich/py_property_testing#1]
Возможно, правильнее было бы реализовать API, используя аннотации: https://peps.python.org/pep-3107/

**Comment by andiogenes** [comment]
Например:

```python
import math.sqrt

def sqrt(x) -> satisfies('sqrt(x) * sqrt(x) == x'):
  return math.sqrt(x)
```

**Comment by dbakunevich** [comment]
По сути с помощью использования аннотаций можно реализовать другой паттерн тестирования. В рамках моей задачи был реализован более гибкий подход к тестированию, в рамках которого возможно проверять работу функции с различными возможными значениями аргументов. 
Пример, который вы привели выше, не может быть однозначно протестирован с помощью аннотаций. Например, как должна вести себя программа, если `x < 0`? Также результат будет неоднозначен, если x - имеет тип float.
